# Generated by Django 6.1 on 2026-09-02 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0018_remove_article_co_authors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('reactions', models.PositiveBigIntegerField(default=0)),
                ('shares', models.PositiveBigIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='publications.article')),
            ],
            options={
                'ordering': ['-date', 'article_id'],
                'indexes': [models.Index(fields=['date'], name='analytics_date_idx'), models.Index(fields=['article', 'date'], name='analytics_article_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'date'), name='unique_article_daily_analytics')],
            },
        ),
    ]
