import type { ReactNode } from "react";
import { ScrollView, StyleSheet, View } from "react-native";
import { colors } from "../theme";
import { SkeletonBlock, SkeletonProvider } from "./Skeleton";

function Screen({ children }: { children: ReactNode }) {
  return <SkeletonProvider><ScrollView style={styles.screen} contentContainerStyle={styles.content} scrollEnabled={false} showsVerticalScrollIndicator={false} accessibilityLabel="Loading content">{children}</ScrollView></SkeletonProvider>;
}
function Heading(){return <View style={styles.headingBlock}><SkeletonBlock style={styles.kicker}/><SkeletonBlock style={styles.heading}/><SkeletonBlock style={styles.line}/><SkeletonBlock style={styles.lineShort}/></View>}
function Card({compact=false}:{compact?:boolean}){return compact?<View style={styles.compactCard}><SkeletonBlock style={styles.compactImage}/><View style={styles.compactCopy}><SkeletonBlock style={styles.smallKicker}/><SkeletonBlock style={styles.cardTitle}/><SkeletonBlock style={styles.cardTitleShort}/><SkeletonBlock style={styles.meta}/></View></View>:<View style={styles.card}><SkeletonBlock style={styles.cardImage}/><View style={styles.cardBody}><SkeletonBlock style={styles.smallKicker}/><SkeletonBlock style={styles.cardTitle}/><SkeletonBlock style={styles.cardTitleShort}/><SkeletonBlock style={styles.line}/><SkeletonBlock style={styles.lineShort}/><SkeletonBlock style={styles.meta}/></View></View>}
function Body({count=7}:{count?:number}){return <View style={styles.body}>{Array.from({length:count},(_,i)=><SkeletonBlock key={i} style={i===count-1?styles.bodyShort:styles.bodyLine}/>)}</View>}
export function HomeSkeleton(){return <Screen><Heading/><Card/><View style={styles.list}><Card compact/><Card compact/><Card compact/></View><View style={styles.section}><Heading/><Card/></View></Screen>}
export function CategorySkeleton(){return <Screen><Heading/><SkeletonBlock style={styles.search}/><Card/><View style={styles.list}><Card/><Card/></View></Screen>}
export function ArticleDetailSkeleton(){return <Screen><View style={styles.articleHeader}><SkeletonBlock style={styles.smallKicker}/><SkeletonBlock style={styles.articleTitle}/><SkeletonBlock style={styles.articleTitleShort}/><SkeletonBlock style={styles.subtitle}/><SkeletonBlock style={styles.metaWide}/></View><SkeletonBlock style={styles.hero}/><View style={styles.articleBody}><SkeletonBlock style={styles.standfirst}/><Body count={9}/><Body count={6}/></View></Screen>}
export function DigitalPublicationsSkeleton(){return <Screen><Heading/><View style={styles.list}>{Array.from({length:4},(_,i)=><View style={styles.publicationCard} key={i}><SkeletonBlock style={styles.cover}/><View style={styles.publicationCopy}><SkeletonBlock style={styles.cardTitle}/><SkeletonBlock style={styles.meta}/><SkeletonBlock style={styles.line}/><SkeletonBlock style={styles.lineShort}/></View></View>)}</View></Screen>}
export function DigitalPublicationDetailSkeleton(){return <Screen><SkeletonBlock style={styles.smallKicker}/><SkeletonBlock style={styles.detailTitle}/><SkeletonBlock style={styles.metaWide}/><SkeletonBlock style={styles.heroCover}/><Body count={4}/><SkeletonBlock style={styles.button}/><SkeletonBlock style={styles.buttonSecondary}/></Screen>}
export function SchoolUpdatesSkeleton(){return <Screen><Heading/><View style={styles.list}><Card/><Card/><Card/></View></Screen>}
export function SchoolUpdateDetailSkeleton(){return <Screen><SkeletonBlock style={styles.smallKicker}/><SkeletonBlock style={styles.detailTitle}/><SkeletonBlock style={styles.metaWide}/><SkeletonBlock style={styles.hero}/><Body count={8}/></Screen>}
export function PeopleSkeleton(){return <Screen><Heading/><View style={styles.peopleGrid}>{Array.from({length:6},(_,i)=><View style={styles.peopleCard} key={i}><SkeletonBlock style={styles.peoplePhoto}/><SkeletonBlock style={styles.peopleName}/><SkeletonBlock style={styles.peopleRole}/></View>)}</View></Screen>}
export function AboutSkeleton(){return <Screen><Heading/><SkeletonBlock style={styles.hero}/><View style={styles.section}><SkeletonBlock style={styles.sectionTitle}/><Body count={6}/></View><View style={styles.section}><SkeletonBlock style={styles.sectionTitle}/><Body count={4}/></View></Screen>}

const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.white},content:{paddingHorizontal:14,paddingTop:28,paddingBottom:56},headingBlock:{marginBottom:22},kicker:{width:96,height:10},smallKicker:{width:82,height:10},heading:{width:"72%",height:34,marginTop:9},line:{width:"100%",height:13,marginTop:11},lineShort:{width:"62%",height:13,marginTop:9},list:{gap:16,marginTop:16},section:{marginTop:34},card:{overflow:"hidden",borderWidth:1,borderColor:colors.line,borderRadius:12,backgroundColor:colors.white},cardImage:{width:"100%",aspectRatio:16/9,borderRadius:0},cardBody:{padding:18},cardTitle:{width:"88%",height:20,marginTop:11},cardTitleShort:{width:"58%",height:20,marginTop:7},meta:{width:"44%",height:11,marginTop:13},compactCard:{flexDirection:"row",gap:13,paddingBottom:15,borderBottomWidth:1,borderBottomColor:colors.line},compactImage:{width:118,height:88,borderRadius:8},compactCopy:{flex:1},search:{width:"100%",height:46,marginBottom:22,borderRadius:10},articleHeader:{marginBottom:22},articleTitle:{width:"94%",height:38,marginTop:10},articleTitleShort:{width:"70%",height:38,marginTop:7},subtitle:{width:"78%",height:18,marginTop:13},metaWide:{width:"56%",height:12,marginTop:16},hero:{width:"100%",aspectRatio:16/9,borderRadius:12},articleBody:{marginTop:24},standfirst:{width:"88%",height:18},body:{gap:10,marginTop:20},bodyLine:{width:"100%",height:13},bodyShort:{width:"63%",height:13},publicationCard:{flexDirection:"row",gap:14,padding:13,borderWidth:1,borderColor:colors.line,borderRadius:12,backgroundColor:colors.white},cover:{width:92,height:126,borderRadius:7},publicationCopy:{flex:1},detailTitle:{width:"86%",height:36,marginTop:10},heroCover:{width:"72%",alignSelf:"center",aspectRatio:.72,marginTop:26,marginBottom:12,borderRadius:8},button:{width:"100%",height:48,marginTop:28,borderRadius:10},buttonSecondary:{width:"100%",height:46,marginTop:10,borderRadius:10},peopleGrid:{flexDirection:"row",flexWrap:"wrap",gap:14},peopleCard:{width:"47%",overflow:"hidden",borderWidth:1,borderColor:colors.line,borderRadius:12,backgroundColor:colors.white,paddingBottom:14},peoplePhoto:{width:"100%",aspectRatio:1,borderRadius:0},peopleName:{width:"72%",height:16,marginTop:13,marginHorizontal:12},peopleRole:{width:"54%",height:11,marginTop:8,marginHorizontal:12},sectionTitle:{width:"42%",height:23}});
