# Generated by Django 6.1 on 2026-08-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_deletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
