# Generated by Django 6.1 on 2026-08-25 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_submission_resubmission_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='draft_type',
            field=models.CharField(choices=[('NORMAL', 'Normal Draft'), ('EDIT_REQUEST', 'Edit Request Draft')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='source_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_drafts', to='publications.article'),
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
