# Generated by Django 6.1 on 2026-08-25 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_article_draft_type_article_source_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='draft_article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_edit_request', to='publications.article'),
        ),
    ]
