# Generated by Django 6.1 on 2026-08-26 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_editrequest_draft_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='snapshot_category_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='snapshot_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='snapshot_featured_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='submission',
            name='snapshot_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='submission',
            name='snapshot_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='SubmissionAttachmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_attachments', to='publications.submission')),
            ],
        ),
    ]
