# Generated by Django 6.1 on 2026-08-31 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_submission_snapshot_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionattachmentsnapshot',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='contentreport',
            name='forced_edit_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_report', to='publications.editrequest'),
        ),
        migrations.AlterField(
            model_name='contentreport',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('REVISION_REQUIRED', 'Revision Required'), ('CANCELLED', 'Cancelled'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=30),
        ),
    ]
