# Generated by Django 6.1 on 2026-08-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_alter_submissionattachmentsnapshot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reaction_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='share_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
