# Generated by Django 6.1 on 2026-09-02 05:38

import publications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0017_add_article_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='co_authors',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='snapshot_co_authors',
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', validators=[publications.validators.validate_article_image]),
        ),
        migrations.AlterField(
            model_name='articleattachment',
            name='image',
            field=models.ImageField(upload_to='articles/attachments/', validators=[publications.validators.validate_article_image]),
        ),
    ]
