# Generated by Django 6.1 on 2026-09-02 07:07

import django.db.models.deletion
import publications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0018_remove_article_co_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='attachment_mode',
            field=models.CharField(choices=[('IMAGE', 'Image Attachments'), ('VIDEO', 'Video Attachments')], default='IMAGE', max_length=10),
        ),
        migrations.AddField(
            model_name='submission',
            name='snapshot_attachment_mode',
            field=models.CharField(blank=True, default='IMAGE', max_length=10),
        ),
        migrations.CreateModel(
            name='ArticleVideoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='articles/video_attachments/', validators=[publications.validators.validate_article_video])),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('credit', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_attachments', to='publications.article')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionVideoAttachmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('credit', models.CharField(blank=True, max_length=255)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_video_attachments', to='publications.submission')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
