# Generated by Django 6.1 on 2026-09-02 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0019_article_attachment_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('change_type', models.CharField(choices=[('INITIAL_PUBLICATION', 'Initial Publication'), ('DIRECT_EDIT', 'Direct Edit'), ('APPROVED_REVISION', 'Approved Revision'), ('CORRECTIVE_REVISION', 'Corrective Revision'), ('BASELINE', 'Existing Published State')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('category_slug', models.CharField(blank=True, max_length=100)),
                ('attachment_mode', models.CharField(choices=[('IMAGE', 'Image Attachments'), ('VIDEO', 'Video Attachments')], default='IMAGE', max_length=10)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('contributors', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('featured_image', models.CharField(blank=True, max_length=500)),
                ('featured_image_caption', models.CharField(blank=True, max_length=255)),
                ('featured_image_credit', models.CharField(blank=True, max_length=255)),
                ('created_by_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='publications.article')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_article_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleVersionImageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('credit', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('article_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_attachments', to='publications.articleversion')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleVersionVideoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('credit', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('article_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_attachments', to='publications.articleversion')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='articleversion',
            constraint=models.UniqueConstraint(fields=('article', 'version_number'), name='unique_article_version_number'),
        ),
    ]
