# Generated by Django 6.1 on 2026-09-04 02:49

import django.db.models.deletion
import publications.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0020_articleversion_articleversionimageattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue_number', models.CharField(blank=True, max_length=50)),
                ('publication_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='digital_publications/covers/', validators=[publications.validators.validate_article_image])),
                ('pdf_file', models.FileField(upload_to='digital_publications/pdfs/', validators=[publications.validators.validate_digital_publication_pdf])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('HIDDEN', 'Hidden')], default='DRAFT', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0, editable=False)),
                ('file_size', models.PositiveBigIntegerField(default=0, editable=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digital_publications_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', '-publication_date', '-created_at'],
            },
        ),
    ]
