# Generated by Django 6.1 on 2026-09-04 09:27

import django.db.models.deletion
import publications.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0021_digitalpublication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(max_length=320)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='school_advertisements/', validators=[publications.validators.validate_article_image])),
                ('is_active', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_advertisements_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_advertisements_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', '-updated_at', '-created_at'],
            },
        ),
    ]
