# Generated by Django 6.1 on 2026-09-04 10:20

import django.db.models.deletion
import publications.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0022_schooladvertisement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About The Equalizer', max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=320)),
                ('overview', models.TextField()),
                ('history', models.TextField()),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about_us/', validators=[publications.validators.validate_article_image])),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='about_us_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'About Us Page',
                'verbose_name_plural': 'About Us Page',
            },
        ),
    ]
