# Generated by Django 6.1 on 2026-09-04 16:16

import django.db.models.deletion
import publications.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0023_aboutuspage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('DEVELOPERS', 'The Developers'), ('CAPSTONE_COMMITTEE', 'Capstone Committee'), ('ICS_FACULTY', 'ICS Faculty'), ('EQUALIZER_TEAM', 'The Equalizer Team')], max_length=30)),
                ('name', models.CharField(max_length=180)),
                ('image', models.ImageField(upload_to='people_profiles/', validators=[publications.validators.validate_article_image])),
                ('role_title', models.CharField(blank=True, max_length=180)),
                ('courses_handled', models.TextField(blank=True)),
                ('school_position', models.CharField(blank=True, max_length=220)),
                ('institute_department', models.CharField(blank=True, max_length=220)),
                ('achievements', models.TextField(blank=True)),
                ('additional_information', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people_profiles_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people_profiles_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section', 'display_order', 'name'],
            },
        ),
    ]
